services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SUPABASE_URL: https://supabase.fireydev.com
        SUPABASE_ANON_KEY: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJzdXBhYmFzZSIsImlhdCI6MTc2NjYwMjkyMCwiZXhwIjo0OTIyMjc2NTIwLCJyb2xlIjoiYW5vbiJ9.ZqSlJJnNDhwOnElfAsMHAMWS61wi2mjBCxLlUW_jbBE
    ports:
      - "8080:80"
    restart: unless-stopped
