#!/usr/bin/env python3
"""Convert a Google My Maps KML export into the boundary GeoJSON that
`BoundaryService` expects.

Why this exists
---------------
The CivSnap boundary matcher (`lib/services/boundary_service.dart`) auto-assigns
each report to a municipal corporation by testing the report's coordinates
against polygons in `lib/assets/data/tt_municipalities.geojson`. That file
ships as a placeholder (rough rectangles). Replace it with your real
municipality boundaries from My Maps using this script.

How to get the KML
------------------
Option A — direct export URL (open in a browser and save the file):

    https://www.google.com/maps/d/kml?mid=1u2BhYRgf7OHjNfXq5BRZZ4l_F4tGm3A&forcekml=1

Option B — in My Maps: ⋮ menu -> "Export to KML/KMZ" -> tick
"Export as KML instead of KMZ" -> download.

Usage
-----
    python3 tools/kml_to_geojson.py path/to/your.kml \
        -o lib/assets/data/tt_municipalities.geojson

Each KML placemark's <name> becomes properties.name. That name must match the
corresponding row in your Supabase `corporations.name` (case-insensitive) so the
boundary service can resolve a corporation_id — or set corporation_id yourself
afterwards.
"""

import argparse
import json
import sys
import xml.etree.ElementTree as ET

KML_NS = "{http://www.opengis.net/kml/2.2}"


def _tag(name: str) -> str:
    return f"{KML_NS}{name}"


def _parse_coordinates(text: str):
    """KML coordinate string 'lng,lat,alt lng,lat,alt ...' -> [[lng, lat], ...]."""
    ring = []
    for chunk in text.split():
        parts = chunk.split(",")
        if len(parts) < 2:
            continue
        try:
            lng = float(parts[0])
            lat = float(parts[1])
        except ValueError:
            continue
        ring.append([lng, lat])
    return ring


def _polygons_from_element(el):
    """Return a list of polygons; each polygon is a list of rings."""
    polygons = []
    for poly in el.iter(_tag("Polygon")):
        rings = []
        outer = poly.find(f"{_tag('outerBoundaryIs')}/{_tag('LinearRing')}/{_tag('coordinates')}")
        if outer is not None and outer.text:
            ring = _parse_coordinates(outer.text)
            if len(ring) >= 3:
                rings.append(ring)
        for inner in poly.findall(f"{_tag('innerBoundaryIs')}/{_tag('LinearRing')}/{_tag('coordinates')}"):
            if inner.text:
                ring = _parse_coordinates(inner.text)
                if len(ring) >= 3:
                    rings.append(ring)
        if rings:
            polygons.append(rings)
    return polygons


def _feature_for_placemark(placemark):
    name_el = placemark.find(_tag("name"))
    name = (name_el.text or "").strip() if name_el is not None else ""
    polygons = _polygons_from_element(placemark)
    if not name or not polygons:
        return None

    if len(polygons) == 1:
        geometry = {"type": "Polygon", "coordinates": polygons[0]}
    else:
        geometry = {"type": "MultiPolygon", "coordinates": polygons}

    return {
        "type": "Feature",
        "properties": {"name": name, "corporation_id": None},
        "geometry": geometry,
    }


def convert(kml_path: str):
    tree = ET.parse(kml_path)
    root = tree.getroot()
    features = []
    skipped = []
    for placemark in root.iter(_tag("Placemark")):
        feature = _feature_for_placemark(placemark)
        if feature is None:
            name_el = placemark.find(_tag("name"))
            skipped.append((name_el.text or "unnamed").strip() if name_el is not None else "unnamed")
            continue
        features.append(feature)
    return {
        "type": "FeatureCollection",
        "_comment": "Generated by tools/kml_to_geojson.py. properties.name must match corporations.name in Supabase.",
        "features": features,
    }, skipped


def main():
    parser = argparse.ArgumentParser(description="Convert My Maps KML to boundary GeoJSON.")
    parser.add_argument("kml", help="Path to the exported .kml file")
    parser.add_argument(
        "-o",
        "--output",
        default="lib/assets/data/tt_municipalities.geojson",
        help="Output GeoJSON path",
    )
    args = parser.parse_args()

    collection, skipped = convert(args.kml)
    if not collection["features"]:
        print("No polygon placemarks found. Is this a My Maps KML with drawn areas?", file=sys.stderr)
        sys.exit(1)

    with open(args.output, "w", encoding="utf-8") as handle:
        json.dump(collection, handle, indent=2)
        handle.write("\n")

    print(f"Wrote {len(collection['features'])} municipality polygon(s) to {args.output}")
    for feature in collection["features"]:
        print(f"  - {feature['properties']['name']}")
    if skipped:
        print("\nSkipped placemarks with no polygon (points/lines):", file=sys.stderr)
        for name in skipped:
            print(f"  - {name}", file=sys.stderr)


if __name__ == "__main__":
    main()
